- name: Test ssh connection to Ubuntu VM
  hosts: linux
  vars:
    ansible_user: azureadmin
    ansible_ssh_private_key_file: /tmp/id_ssh_rsa
    host_key_checking: false
  tasks:
  - name: Test SSH connection
    ansible.builtin.ping: